name: Hello-world

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build-step
        run: echo "A Demo build"
  test:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Test-step
          run: echo "All Test Cases are Passed"
  Deploy:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Deploy-step
          run: echo "All are deployed"
